<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/** @var Renderer $block */
/** @var Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

?>
<tbody class="bg-white border-b-2 cart item lg:flex lg:flex-row lg:justify-between lg:items-center">
    <tr class="flex flex-col text-left align-top item-info lg:text-right sm:flex-wrap lg:table-row lg:w-2/4">
        <th class="hidden px-4 pt-4 pb-2 text-left col item" scope="col">
            <?= $escaper->escapeHtml(__('Item')) ?>
        </th>
        <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="flex flex-col-reverse items-center w-full gap-2 px-4 py-3 text-left xl:flex-row col item">
            <?php if ($block->hasProductUrl()) : ?>
                <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>" title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>" tabindex="-1" class="flex-shrink-0 product-item-photo">
                <?php else : ?>
                    <span class="flex-shrink-0 product-item-photo">
                    <?php endif; ?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                        ->setTemplate('Magento_Catalog::product/image.phtml')
                        ->toHtml() ?>
                    <?php if ($block->hasProductUrl()) : ?>
                </a>
            <?php else : ?>
                </span>
            <?php endif; ?>
            <div class="flex-grow xl:text-center product-item-details">
                <strong class="pb-2 text-lg font-medium tracking-tighter break-all product-item-name">
                    <?php if ($block->hasProductUrl()) : ?>
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>">
                            <?= $escaper->escapeHtml($block->getProductName()) ?>
                        </a>
                    <?php else : ?>
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($options = $block->getOptionList()) : ?>
                    <dl class="clearfix w-full pb-2 mt-4 text-sm break-all item-options">
                        <?php foreach ($options as $option) : ?>
                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                            <dt class="float-left mb-2 mr-2 font-bold clear-left">
                                <?= $escaper->escapeHtml($option['label']) ?>:
                            </dt>
                            <dd class="float-left">
                                <?php if (isset($formatedOptionValue['full_view'])) : ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                                <?php else : ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php if ($messages = $block->getMessages()) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                            <div>
                                <?= $escaper->escapeHtml($message['text']) ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($item)->toHtml() ?>
                <?php endif; ?>
            </div>
        </td>

    <tr class="grid flex-row items-center grid-cols-3 pb-12 sm:flex lg lg:pb-3 gap-x-5 xl:w-auto">
        <td class="w-full pt-6 pl-4 pr-4 col price lg:pl-8 sm:w-1/3 lg:w-auto lg:table-cell">
            <span class="flex justify-start mt-2 font-medium text-customlightblue">
                <?= $escaper->escapeHtml(__('Price')) ?>
            </span>
            <?= $block->getUnitPriceHtml($item) ?>
        </td>

        <td class="block w-full px-4 col qty lg:pt-3 sm:w-1/3 lg:w-auto lg:table-cell">
            <span class="justify-center hidden mt-2 font-medium">
                <?= $escaper->escapeHtml(__('Qty')) ?>
            </span>
            <div class="field qty">
                <div class="control qty">
                    <label class="-mb-6" for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                        <span class="sr-only label">
                            <?= $escaper->escapeHtml(__('Qty')) ?>
                        </span>
                        <input id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty" name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]" value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>" type="number" size="4" step="any" title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>" class="w-12 px-1 text-center border-b-2 qty form-input sm:px-2 sm:py-2 border-b-customlightblue " required="required" min="0" data-role="cart-item-qty" />
                    </label>
                </div>
            </div>
        </td>

        <td class="block w-full px-4 pt-6 col subtotal sm:w-1/3 lg:w-auto lg:table-cell">
            <span class="flex justify-start mt-2 font-medium text-customlightblue">
                <?= $escaper->escapeHtml(__('Subtotal')) ?>
            </span>
            <?= $block->getRowTotalHtml($item) ?>
        </td>
        <td colspan="4" class="flex lg:hidden lg:w-1/3">
            <div class="flex items-center justify-end gap-4 pt-1 pr-5 mt-5">
                <?= /* @noEscape */ $block->getActions($item) ?>
            </div>
        </td>
    </tr>
    </tr>
    </tr>
    <td colspan="4" class="hidden lg:flex lg:w-1/3">
        <div class="flex items-center justify-end gap-4 pt-1 pr-5 mt-5">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </div>
    </td>

</tbody>