<?php
declare(strict_types=1);

/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

use MageWorx\Locations\Api\Data\LocationInterface;

/** @var $block \MageWorx\StoreLocator\Block\LocationDetail */
/** @var $location LocationInterface $location */
/** @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroicons */
/** @var $escaper \Magento\Framework\Escaper */

$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);
$location = $block->getLocation(); ?>

<div id="location-details_<?= $escaper->escapeHtml($location->getId()) ?>" x-data="{isShowWorkTable:false}" class="overflow-y-visible">
    <ul class="flex flex-col gap-y-2">
        <li class="py-4 font-bold"><?= /* @noEscape */
            $block->getLocationPageLink($location, __('Store Page')) ?>
        </li>

        <?= /** @noEscape */ $block->getWorkingHoursHtml($location) ?>

        <?php if ($location->getPhoneNumber()) : ?>
            <li class="flex gap-x-4">
                <?= $heroicons->phoneHtml('w-6 h-6') ?>
                <a href="tel:<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getPhoneNumber())); ?>">
                    <?= $escaper->escapeHtml($location->getPhoneNumber()); ?>
                </a>
            </li>
        <?php endif; ?>
        <?php if ($location->getEmail()) : ?>
            <li class="flex gap-x-4">
                <?= $heroicons->atSymbolHtml('w-6 h-6') ?>
                <a href="mailto: <?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getEmail())); ?>"
                   target="_blank">
                    <?= $escaper->escapeHtml($location->getEmail()); ?>
                </a>
            </li>
        <?php endif; ?>
        <?php if ($location->getWebsiteUrl()) : ?>
            <li class="flex gap-x-4">
                <?= $heroicons->globeAltHtml('w-6 h-6') ?>
                <a href="https://<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getWebsiteUrl())); ?>"
                   target="_blank">
                    <?= $escaper->escapeHtml($location->getWebsiteUrl()); ?>
                </a>
            </li>
        <?php endif; ?>
        <li class="mt-4">
            <ul class="flex gap-x-4">
                <?php if ($location->getInstagram()) : ?>
                    <li>
                        <a href="https://instagram.com/<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getInstagram())); ?>"
                           target="_blank">
                            <i>
                                <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl(
                                    $block->getViewFileUrl('MageWorx_StoreLocator::images/svg/instagram.svg')
                                )); ?>" alt="<?= $escaper->escapeHtml(__('Instagram icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($location->getFacebook()) : ?>
                    <li>
                        <a href="https://facebook.com/<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getFacebook())); ?>"
                           target="_blank">
                            <i>
                                <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl(
                                    $block->getViewFileUrl(
                                        'MageWorx_StoreLocator::images/svg/facebook.svg'
                                    )
                                )); ?>" alt="<?= $escaper->escapeHtml(__('Facebook icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($location->getWhatsapp()) : ?>
                    <li>
                        <a href="https://wa.me/<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getWhatsapp())); ?>" target="_blank">
                            <i>
                                <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl(
                                    $block->getViewFileUrl('MageWorx_StoreLocator::images/svg/whatsapp.svg')
                                )); ?>" alt="<?= $escaper->escapeHtml(__('Whatsapp icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($location->getSkype()) : ?>
                    <li>
                        <a href="skype:<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getSkype())); ?>?call">
                            <i>
                                <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl(
                                    $block->getViewFileUrl('MageWorx_StoreLocator::images/svg/skype.svg')
                                )); ?>" alt="<?= $escaper->escapeHtml(__('Skype icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
    <div>
        <div class="mw-extra_attr_columns">
            <ul class="flex gap-x-6 items-center">
                <?php foreach ($block->getExtraAttributes() as $attribute) : ?>
                    <?php if ($location->getData($attribute['attribute_code'])) : ?>
                        <li class="flex gap-x-2 items-center">
                            <i>
                                <?php $icon = $block->getAttributeIcon($attribute['attribute_code']);
                                if ($icon): ?>
                                    <img class="w-4 h-4"
                                         src="<?= $escaper->escapeUrl($icon); ?>"
                                         alt="<?= $escaper->escapeHtml(__($attribute['frontend_label'])) ?>"/>
                                <?php endif;?>
                            </i>
                            <span><?= $escaper->escapeHtml(__($attribute['frontend_label'])) ?><span>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="mt-2">
        <?= /* @noEscape */ $location->getDescription() ?>
    </div>
</div>
