<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package Cash on Delivery for Magento 2
 */

use Armah\CashOnDelivery\Block\Checkout\Cart\CheckAvailable;
use Magento\Framework\Escaper;

/** @var CheckAvailable $block */
/** @var Escaper $escaper */
?>

<?php if ($block->isVerificationEnable()): ?>
    <div id="block-arcashondelviery"
         class="block arcashondelviery"
         data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
        <div class="title" data-role="title">
            <strong id="block-arcashondelviery-heading" role="heading" aria-level="2">
                <?= $escaper->escapeHtml(__('Check Cash on Delivery Availability for Your ZIP')) ?>
            </strong>
        </div>
        <div id="block-arcashondelviery-summary"
             data-bind="scope:'block-arcashondelviery-summary'"
             class="content" data-role="content"
             aria-labelledby="block-arcashondelviery-heading">
            <div hidden data-arcashdel-js="allowed-postal-code" class="arcashdel-success">
                <?= $escaper->escapeHtml(__('Cash on Delivery is available')) ?>
            </div>
            <div hidden data-arcashdel-js="not-allowed-postal-code" class="arcashdel-error">
                <?= $escaper->escapeHtml(__('Cash on Delivery is not available')) ?>
            </div>
            <div class="arcashdel-input-wrapper">
                <input type="text"
                       class="input-text arcashdel-input"
                       id="postal_code"
                       name="postal_code"
                       value=""
                       placeholder="<?= $escaper->escapeHtml(__("Enter your postal code here")) ?>"
                       data-mage-init='{"arCodCheckAvailable": {}}'
                >
                <button type="button"
                        class="action primary arcashdel-btn"
                        data-arcashdel-js="arcashdel-check-status">
                    <?= $escaper->escapeHtml(__('Check')) ?>
                </button>
            </div>
        </div>
    </div>
<?php endif; ?>
