<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig(
    "checkout/sidebar/max_items_display_count"
);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
use Hyva\Theme\ViewModel\SvgIcons;
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            totalCartAmount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.totalCartAmount = this.cart.summary_count;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('(%0 <?= $escaper->escapeJs(
                    __("of")
                ) ?> %1)', this.maxItemsToDisplay, this.itemsCount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(
                                __("Could not remove item from quote.")
                            ) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(
                                __("You removed the item.")
                            ) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            }
        }
    }
</script>
<section id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getData($event.detail.data)"
         @toggle-cart.window="open=true"
         @keydown.window.escape="open=false"
>
    <template x-if="cart && cart.summary_count">
        <div role="dialog"
             aria-labelledby="cart-drawer-title"
             aria-modal="true"
             @click.away="open=false"
             class="fixed inset-y-0 right-0 z-[100] flex max-w-full">
            <div class="backdrop"
                 x-show="open"
                 x-transition:enter="ease-in-out duration-500"
                 x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100"
                 x-transition:leave="ease-in-out duration-500"
                 x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0"
                 @click="open=false"
                 aria-label="Close panel"></div>
            <div class="relative w-screen shadow-2xl lg:max-w-xl"
                 x-show="open"
                 x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:enter-start="translate-x-full"
                 x-transition:enter-end="translate-x-0"
                 x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:leave-start="translate-x-0"
                 x-transition:leave-end="translate-x-full"
            >
                <div
                    x-show="open"
                    x-transition:enter="ease-in-out duration-500"
                    x-transition:enter-start="opacity-0"
                    x-transition:enter-end="opacity-100"
                    x-transition:leave="ease-in-out duration-500"
                    x-transition:leave-start="opacity-100"
                    x-transition:leave-end="opacity-0" class="absolute top-0 right-0 flex p-2 mt-2">
                    <button @click="open=false" aria-label="Close panel"
                            class="p-2 text-gray-300 transition duration-150 ease-in-out hover:text-black">
                        <?= $heroicons->xHtml() ?>
                    </button>
                </div>
                <div class="flex flex-col h-full py-6 space-y-6 bg-white shadow-xl">
                    <header class="px-4 sm:px-6">
                        <h2 id="cart-drawer-title" class="w-1/4 -mt-3 text-3xl font-bold text-black border-b border-rosso">
                            <?= $escaper->escapeHtml(__("My Cart")) ?>
                            <span class="text-xs items-total"
                                  x-show="maxItemsToDisplay && maxItemsToDisplay < itemsCount"
                                  x-text="getItemCountTitle()">
                            </span>
                        </h2>
                    </header>
                    <div class="relative grid gap-6 px-4 py-6 overflow-y-auto bg-white border-b sm:gap-8 sm:px-6 border-container">
                        <template x-for="item in cartItems">
                            <div class="flex items-start p-3 -m-3 space-x-4 transition duration-150 rounded-none ease-in-outs hover:bg-gray-100">
                                <a :href="item.product_url" class="">
                                    <img
                                        :src="item.product_image.src"
                                        :width="item.product_image.width"
                                        :height="item.product_image.height"
                                        loading="lazy"
                                    />
                                </a>
                                <div class="w-3/4 space-y-2">
                                    <div>
                                        <p class="text-[1.10rem] font-medium leading-6">
                                            <span x-html="item.qty"></span> x <span x-html="item.product_name"></span>
                                        </p>
                                        <p class="text-sm tracking-widest"><span x-html="item.product_sku"></p>
                                    </div>
                                    <template x-for="option in item.options">
                                        <div class="pt-2 hidden">
                                            <p class="font-semibold" x-text="option.label + ':'"></p>
                                            <p class="text-secondary" x-html="option.value"></p>
                                        </div>
                                    </template>
                                    <div class="flex items-center justify-between pt-1">
                                        <p><span class="text-2xl text-rosso" x-html="item.product_price"></span></p>
                                        <div class="mr-5">
                                            <a :href="item.configure_url"
                                            x-show="item.product_type !== 'grouped'"
                                            class="inline-flex p-2 mr-2 rounded-full btn bg-arancio hover:bg-arancio-600">
                                                <?= $hyvaicons->matitaHtml(
                                                    "",
                                                    20,
                                                    20
                                                ) ?>
                                            </a>
                                            <button class="inline-flex p-2 rounded-full btn bg-arancio hover:bg-arancio-600"
                                                @click="deleteItemFromCart(item.item_id)"
                                            >
                                                <?= $hyvaicons->cestinoHtml(
                                                    "",
                                                    20,
                                                    20
                                                ) ?>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </template>
                    </div>
                    <div class="relative grid gap-6 px-4 py-6 bg-white sm:gap-8 sm:px-6">
                        <div class="w-full p-3 -m-3 space-x-4 transition duration-150 ease-in-out rounded-sm hover:bg-gray-100">
                            <p class="font-semibold"><?= $escaper->escapeHtml(
                                __("Subtotal")
                            ) ?>: <span class="text-2xl text-rosso" x-html="cart.subtotal"></span></p>
                        </div>
                        <div class="flex flex-col -m-3 transition duration-150 ease-in-out">
                            <a href="<?= $escaper->escapeUrl(
                                $block->getUrl("checkout")
                            ) ?>"
                                class="inline-flex justify-center py-3 mb-3 text-xl font-bold rounded-lg btn bg-rosso hover:bg-rosso-600">
                                <?= $escaper->escapeHtml(__("Go to Checkout")) ?>
                            </a>
                            <div class="flex items-baseline justify-center mb-1">
                            
                            <a href="<?= $escaper->escapeUrl(
                                $block->getUrl("checkout/cart")
                            ) ?>"
                               class="inline-flex justify-center w-full py-3 mb-3 text-xl font-bold rounded-lg btn bg-arancio hover:bg-arancio-600">
                                <?= $escaper->escapeHtml(
                                    __("View and Edit Cart")
                                ) ?>
                            </a>
                            </div>
                        </div>
                        <?= $block->getChildHtml("extra_actions") ?>
                    </div>
                </div>
            </div>
            <?= $block->getChildHtml("loading") ?>
        </div>
    </template>
</section>
