<?php
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

/** @var \Hyva\StripeIntegrationPayments\ViewModel\ProductButton $viewModels */
$viewModel = $viewModels->require(Hyva\StripeIntegrationPayments\ViewModel\ProductButton::class);
$uniqueSciptId = md5($block->getNameInLayout());
?>
<?php if ($block->isEnabled('product_page')) : ?>

    <?php
    // In load order.
    $scripts = [
        'https://js.stripe.com/v3/',
        'Hyva_StripeIntegrationPayments::js/stripe_payments_express_hyva.js'
    ];
    ?>

    <script defer>
        function stripeExpressPaymentsProductButtonBridgeComponent_<?= $uniqueSciptId ?>() {

            function loadScript(url) {
                return new Promise((resolve) => {
                    // Check if the script is already loaded and in the document
                    const existingScript = document.querySelector(`script[src="${url}"]`);

                    if (existingScript) {
                        // Check if the script is already loaded
                        if (existingScript.readyState === 'complete' || existingScript.readyState === 'loaded') {
                            resolve();
                        } else {
                            // If not loaded yet, listen for the load event
                            existingScript.addEventListener('load', resolve);
                        }
                        return;
                    }

                    let script = document.createElement('script');
                    script.setAttribute('type', 'text/javascript');
                    script.setAttribute('src', url);
                    document.head.append(script);

                    script.addEventListener('load', resolve);
                });
            }

            return {
                isInitialized: false,
                loading: false,
                loadScripts: function () {
                    if (this.isInitialized) {
                        return;
                    }

                    if (typeof window.stripePaymentsExpressHyvaBridgeScriptsInstalled !== 'undefined' && window.stripePaymentsExpressHyvaBridgeScriptsInstalled === true) {
                        this.postInit();
                        return;
                    }

                    var promises = [
                        <?php foreach($scripts as $scriptUrl): ?>
                        <?php
                        $parsedScriptUrl = $viewModel->getAssetUrl($scriptUrl);
                        if (substr($scriptUrl, 0, 4) === "http") {
                            $parsedScriptUrl = $scriptUrl;
                        }
                        ?>
                        loadScript('<?= $escaper->escapeJs($parsedScriptUrl) ?>'),
                        <?php endforeach; ?>
                    ];

                    // All files loaded, migrate to postInit phase.
                    Promise.all(promises).then(() => {
                        this.postInit();
                    });
                },

                isLoading() {
                    return this.loading;
                },

                preInit: function() {
                    this.loadScripts();
                },
                postInit: function() {
                    window.stripePaymentsExpressHyvaBridgeScriptsInstalled = true;
                    this.isInitialized = true;
                    var locationDetails = {
                        location: 'product',
                        productId: '<?= $block->getProductId(); // phpcs:ignore ?>',
                    };
                    stripePaymentsExpressHyvaBridge.initStripeExpress(
                        '#payment-request-button',
                        <?= $block->initParams->getWalletParams(); // phpcs:ignore ?>,
                        locationDetails,
                        <?= $block->getButtonConfig(); // phpcs:ignore ?>,
                        stripePaymentsExpressHyvaBridge.initProductWidget.bind(stripePaymentsExpressHyvaBridge),
                        this
                    );
                }
            };
        }

        window.addEventListener(
            'alpine:init',
            () => Alpine.data(
                'stripeExpressPaymentsProductButtonBridgeComponent_<?= $uniqueSciptId ?>',
                stripeExpressPaymentsProductButtonBridgeComponent_<?= $uniqueSciptId ?>
            ),
            {once: true}
        )
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>

    <div class="flex justify-end w-full" x-data="stripeExpressPaymentsProductButtonBridgeComponent_<?= $uniqueSciptId ?>" x-init="preInit">
        <div id="payment-request-button" class="action tocart w-full">&nbsp;</div>
        <?= $block->getChildHtml('product.info.stripe_loading') ?>
    </div>
<?php endif; ?>
