<?php

/** @var \Armah\Base\Block\Import $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/alert',
            'prototype'
        ], function($) {
            //<![CDATA[
            var entity = $('#entity');
            entity.hide();
            entity.closest('fieldset').find('label.label.admin__field-label').css('visibility','hidden');
            $(entity).val('<?= $escaper->escapeHtml($block->getImportEntity()) ?>');
            varienImport.handleEntityTypeSelector();
            //]]>
        }
    );
</script>
