<?php

/** @var \Armah\Base\Block\Adminhtml\Messages $block */
$messages = $block->getMessages();
?>
<?php if (!empty($messages)): ?>
    <?php foreach ($messages as $message): ?>
        <div class="messages arbase-unsubscribe">
            <div class="message message-success success">
                <div data-ui-id="messages-message-success"><?= /* @noEscape */ $message;?></div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
