<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package Custom Checkout Fields for Magento 2
 */
/**
 * @var \Armah\Orderattr\Block\Paypal\Attributes $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<div data-block="order-attributes" data-bind="scope: 'arorder_attributes_fields'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script>
    window.checkoutConfig = <?= /* @noEscape */ $block->getCheckoutConfig() ?>;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
</script>
<script>
    require([
        'mage/url'
    ], function(url) {
        return url.setBaseUrl('<?= $escaper->escapeJs($escaper->escapeUrl($block->getBaseUrl())) ?>');
    })
</script>

<script type="text/x-magento-init">
    {
        "[data-block='order-attributes']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
