<?php
declare(strict_types=1);

/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

?>
<?php
/**
 * Location List view template
 *
 * @var $block MageWorx\LocationPages\Block\LocationList
 */

/** @var $escaper \Magento\Framework\Escaper */

/** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
$location = $block->getCurrentLocationList();
$children = $block->getChildLocations(); ?>
<div id="mw-store-locator-countries">
    <ul class="flex flex-col gap-y-2">
        <?php if (count($children)) :
            foreach ($children as $item) : ?>
                <li>
                    <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($item->getFullUrl())) ?>">
                        <?= $escaper->escapeHtml($item->getName()) ?>
                        <?php if ($item->getLocationCount()) : ?>
                        <span>(<?= $escaper->escapeHtml($item->getLocationCount())?>)</span></a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</div>
