<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package One Step Checkout Core for Magento 2
 */
    /** @var \Armah\CheckoutCore\Block\Adminhtml\Renderer\Template $block */
    /** @var \Magento\Framework\Escaper $escaper */
?>

<?php if (!$block->isOrderAttributesEnable()): ?>
    <div class="fields-comment message">
        <?= $escaper->escapeHtml(__('Need more custom fields? Please consider')) ?>
        <a href="https://armah.it/order-attributes-for-magento-2.html" target="_blank">
            <?= $escaper->escapeHtml(__('Order Attributes')) ?>
        </a><?= $escaper->escapeHtml(__(' extension.')) ?>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Armah_CheckoutCore/js/view/checkout-fields": {}
        }
    }
</script>
