<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove;
use Magento\Framework\Escaper;

/** @var Remove $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);

?>
<a href="#"
   title="<?= $escaper->escapeHtml(__('Remove item')) ?>"
   class="inline-flex p-2 rounded-full action action-delete btn btn-primary bg-arancio hover:bg-arancio-600"
   x-data="{}"
   @click.prevent='hyva.postForm(<?= /* @noEscape */ $block->getDeletePostJson() ?>)'
>
    <?= $heroicons->trashHtml('h-4 sm:h-6 w-4 sm:w-6') ?>
    <span class="sr-only"><?= $escaper->escapeHtml(__('Remove item')) ?></span>
</a>
