<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) 2023 Armah (https://www.armah.it)
 * @package Cron Schedule List for Magento 2 (System) 
 */ /** @var \Armah\CronScheduleList\Block\Adminhtml\Advertising $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<div class="armah_cron_advertising_banner">
    <div class="message">
        <p>
            <?= $escaper->escapeHtml(__('Efficiently track and manage all cron tasks running '
                . 'in the website background with')); ?><b> Magento 2 Cron Scheduler extension.</b>
            <a href="<?= $escaper->escapeUrl($block->getLink()); ?>" target="_blank">
                <button class="action- scalable primary">
                    <span>
                        <?= $escaper->escapeHtml(__('Visit page')); ?>
                    </span>
                </button>
            </a>
        </p>
    </div>
</div>
