<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah
 * @package Improved Sorting Hyva Compatibility by Armah
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;
use Armah\SortingHyvaCompatibility\ViewModel\WidgetListItem;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var WidgetListItem $widgetViewModel */
$widgetViewModel = $viewModels->require(WidgetListItem::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);


/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @var Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled() && !$block->getData('hide_wishList');
$showAddToCompare = $compareViewModel->showInProductList() && !$block->getData('hide_compare');
$viewIsGrid = $viewMode === 'grid';
$productListType = $block->getData('list_type');

$isImagesOnlyType = $productListType === $widgetViewModel::IMAGES_ONLY_TYPE;
$isNamesOnlyType = $productListType === $widgetViewModel::NAMES_ONLY_TYPE;
$isFullViewType = $productListType === $widgetViewModel::FULL_VIEW_TYPE;

if (!$product) {
    return '';
}
$productId = $product->getId();
$options   = $productOptionsViewmodel->getOptionsData($product);
$uniqueId = '_' . uniqid();

$hideDetails       = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
?>
<?php if ($product->isSaleable() && $isFullViewType): ?>
<form method="post"
    action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
    class="item product product-item product_addtocart_form card card-interactive flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>"
    role="form"
    aria-label="<?= $escaper->escapeHtml(__('Add to cart %1 form', $product->getName())) ?>"
    <?php if ($product->getOptions()): ?>
    enctype="multipart/form-data"
    <?php endif; ?>
>
    <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="product" value="<?= (int)$productId ?>"/>
    <?php foreach ($options as $optionItem): ?>
    <input type="hidden"
           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
    <?php endforeach; ?>
    <?php else: ?>
<div class="item product product-item <?= $isFullViewType ? 'card card-interactive' : ''; ?> flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>">
<?php endif; ?>
    <?php if ($isFullViewType || $isImagesOnlyType): ?>
        <?php /* Product Image */ ?>
        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
           class="product photo product-item-photo block mx-auto mb-3 <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5' ?>"
           tabindex="0"
        >
            <?= $block->getImage($product, $imageDisplayArea)
                ->setTemplate('Magento_Catalog::product/list/image.phtml')
                ->setData('custom_attributes', $imageCustomAttributes)
                ->setProductId($productId)
                ->toHtml(); ?>
        </a>
    <?php endif; ?>
    <?php if ($isFullViewType || $isNamesOnlyType): ?>
        <div class="product-info flex flex-col grow">
            <div class="mt-2 mb-1 items-center justify-center text-primary <?= $isFullViewType ? 'font-semibold text-lg text-center' : 'hover:underline' ; ?> <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                <a class="product-item-link"
                   href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <?= $escaper->escapeHtml($product->getName()) ?>
                </a>
            </div>
            <?php if ($isFullViewType): ?>

                <?php if (!$hideRatingSummary): ?>
                <div class="py-1 mx-auto <?= $viewIsGrid ? '' : 'md:mx-0 md:w-auto' ?>">
                    <?= $block->getReviewsSummaryHtml($product, 'short') ?>
                </div>
                <?php endif; ?>

                <?php if ($product->isAvailable() && !$hideDetails): ?>
                    <?= $block->getProductDetailsHtml($product) ?>
                <?php endif; ?>

                <?php if ($showDescription): ?>
                <div class="mt-2 mb-1 items-center justify-center text-primary text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                    <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
                </div>
                <?php endif; ?>

                <script>
                    function initPriceBox_<?= /** @noEscape */ $uniqueId ?>()
                    {
                        return {
                            updatePrice(priceData) {
                                const regularPriceLabel = this.$root.querySelector('.normal-price .price-label');
                                const regularPriceElement = this.$root.querySelector('.normal-price [data-price-type=finalPrice].price-wrapper .price');
                                const basePriceElement = this.$root.querySelector('.normal-price [data-price-type=basePrice].price-wrapper .price');
                                if (priceData.finalPrice.amount < priceData.oldPrice.amount) {
                                    regularPriceLabel.classList.add('hidden');
                                } else {
                                    regularPriceLabel.classList.remove('hidden');
                                }
                                regularPriceElement.innerText = hyva.formatPrice(priceData.finalPrice.amount);
                                basePriceElement && (basePriceElement.innerText = hyva.formatPrice(priceData.basePrice.amount));
                            },
                            eventListeners: {
                                '@update-prices-<?= (int)$productId ?>.window'(event) {
                                    this.updatePrice(event.detail);
                                }
                            }
                        }
                    }

                    window.addEventListener(
                        'alpine:init',
                        () => Alpine.data('initPriceBox_<?= /** @noEscape */ $uniqueId ?>', initPriceBox_<?= /** @noEscape */ $uniqueId ?>),
                        {once: true}
                    );
                </script>
                <?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>

                <div class="pt-1 text-gray-900"
                     x-data="initPriceBox_<?= /** @noEscape */ $uniqueId ?>"
                >
                    <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
                </div>

                <div class="mt-auto pt-3 flex flex-wrap justify-center items-center">
                    <?php if ($product->isSaleable()): ?>
                    <button class="w-auto btn btn-primary justify-center text-sm
                            <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>">
                        <?= $heroicons->shoppingCartHtml("h-6 w-6 border-current inline", 25, 25) ?>
                        <span class="ml-2 inline <?= $viewIsGrid ? 'md:ml-0 md:hidden lg:ml-2 lg:inline' : '' ?>">
                            <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                        </span>
                    </button>
                    <?php else: ?>
                    <div class="w-auto justify-center <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>">
                        <?= $block->getChildBlock('stockstatus')->setData('product', $product)->toHtml() ?>
                    </div>
                    <?php endif; ?>
                    <?php if ($showAddToWishlist): ?>
                        <button x-data="initWishlist"
                                @click.prevent="addToWishlist"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                type="button"
                                class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2">
                            <?= $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
                        </button>

                        <script>
                            function initWishlistComponent() {
                                return Object.assign(
                                    initWishlist(),
                                    {
                                        addToWishlist() {
                                            initWishlist()?.addToWishlist(<?= (int)$productId ?>);
                                        }
                                    }
                                )
                            }

                            window.addEventListener('alpine:init', () => Alpine.data('initWishlistComponent', initWishlistComponent), {once: true});
                        </script>
                        <?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
                    <?php endif; ?>
                    <?php if ($showAddToCompare): ?>
                        <button x-data="initCompareOnProductListComponent"
                                @click.prevent="addToCompare"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                type="button"
                                class="rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-yellow-500 ml-2">
                            <?= $heroicons->scaleHtml("w-5 h-5", 25, 25) ?>
                        </button>

                        <script>
                            function initCompareOnProductListComponent() {
                                return Object.assign(
                                    initCompareOnProductList(),
                                    {
                                        addToCompare() {
                                            initCompareOnProductList()?.addToCompare(<?= (int)$productId ?>);
                                        }
                                    }
                                )
                            }

                            window.addEventListener('alpine:init', () => Alpine.data('initCompareOnProductListComponent', initCompareOnProductListComponent), {once: true});
                        </script>
                        <?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
                    <?php endif; ?>
                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                        <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php if ($product->isSaleable() && $isFullViewType): ?>
</form>
<?php else: ?>
</div>
<?php endif; ?>
