<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package One Step Checkout Delivery Date for Magento 2 (System)
 */
/** @var \Armah\CheckoutDeliveryDate\Block\Adminhtml\Sales\Order\Create\Deliverydate $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
</section><section class="admin__page-section armah-deliverydate">
    <div class="admin__page-section-title">
        <span class="title"><?= $escaper->escapeHtml(__('Delivery Information')) ?></span>
    </div>
    <?php foreach ($block->getFormElements() as $element): ?>
        <?= /* @noEscape */ $element->toHtml() ?>
    <?php endforeach; ?>
