<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package One Step Checkout Delivery Date for Magento 2 (System)
 */
/** @var $block Armah\CheckoutDeliveryDate\Block\Config\DDLayoutBuilder */
?>

<script type="text/javascript">
    if (!window.armahCheckoutConfig) {
        window.armahCheckoutConfig = {};
    }

    window.armahCheckoutConfig.deliveryDateInstalled = true;
</script>

