<?php if ($block->isKlaviyoEnabled() && $block->getPublicApiKey()): ?>
    <div x-data="initKlaviyoCartTracking()" x-init="sendKlaviyoCartData()"></div>
    <script>
        function initKlaviyoCartTracking() {
            return {
                sendKlaviyoCartData() {
                    fetch(
                        '/reclaim/checkout/reload?form_key=' + hyva.getFormKey(),
                        {
                            method: 'POST',
                            body: {},
                            headers: {contentType: 'application/json'}
                        }
                    )
                }
            }
        }
    </script>
<?php endif; ?>

