<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="flex flex-col justify-center w-full pt-10 my-8 border-t lg:border-t-0 lg:pt-0 lg:border-l block-new-customer md:w-1/2 md:my-0">
        <div class="block-title">
        <?= $block->getBlockHtml('page.main.title') ?>
            <h2 class="mb-3 text-3xl font-bold text-center text-gray-600 title-font" role="heading"
                aria-level="2"><?= $escaper->escapeHtml(__('Welcome to login')) ?></h2>
        </div>
        <div class="mt-4 text-center block-content" aria-labelledby="block-new-customer-heading">
            <p>
                <?= $escaper->escapeHtml( // phpcs:disable Generic.Files.LineLength.TooLong
                    __("Don't you have an account?")
                ) // phpcs:enable ?>
            </p>
        </div>
        <div class="flex justify-center pt-2 pb-2">
            <a href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>"
               class="rounded-md btn bg-rosso hover:bg-rosso-600"><span><?= $escaper->escapeHtml(__('Sign Up')) ?></span></a>
        </div>
    </div>
<?php endif; ?>
