<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\CmsTailwindJit\ViewModel\CategoryTailwindCss;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentCategory;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var CurrentCategory $currentCategory */
/** @var CategoryTailwindCss $categoryCss */

$currentCategory = $viewModels->require(CurrentCategory::class);
if (! $currentCategory->exists()) {
    return;
}

$categoryCss       = $viewModels->require(CategoryTailwindCss::class);
$attributeCodes    = ['description']; // List of category attributes with Tailwind classes to be styled/prefixed
$styles            = $categoryCss->getStylesForCategoryAttributes($currentCategory->get(), $attributeCodes);

if ($styles): ?>
<style><?= /** @noEscape */ $styles ?></style>
<?php endif; ?>
