<?php

declare(strict_types=1);

/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package SEO Toolkit Base for Magento 2
 */

namespace Armah\SeoToolkitLite\Setup\Patch\Data;

use Armah\SeoToolkitLite\Api\Data\RedirectInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;

class SetUndefinedPageSettings implements DataPatchInterface
{
    /**
     * @var ModuleDataSetupInterface
     */
    private $setup;

    public function __construct(
        ModuleDataSetupInterface $setup
    ) {
        $this->setup = $setup;
    }

    public static function getDependencies(): array
    {
        return [];
    }

    public function getAliases(): array
    {
        return [];
    }

    public function apply(): void
    {
        $redirectTable = $this->setup->getTable(RedirectInterface::TABLE_NAME);

        $this->setup->getConnection()->update(
            $redirectTable,
            [RedirectInterface::UNDEFINED_PAGE_ONLY => 1],
            [RedirectInterface::IS_AUTOGENERATED . ' = ?' => 1]
        );
    }
}
