<?php
declare(strict_types=1);

/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

/** @var HeroIconsOutline $heroIcons */
$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);

/** @var $escaper \Magento\Framework\Escaper */
?>
<?php
/**
 * Location Page view template
 *
 * @var $block MageWorx\LocationPages\Block\Location
 */
/** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
$location = $block->getCurrentLocation();
if ($location) :?>
    <script>
        function initMwLocatorDetailsPage() {
            const config = {
                openNow: "<?= $escaper->escapeJS(__('Open now')); ?>",
                closedNow: "<?= $escaper->escapeJS(__('Closed now')); ?>",
                isWorkingHoursEnabled: <?= ($block->isWorkingHoursEnabled($location)) ? "true" : "false" ?>
            }

            return {
                init() {
                    this.isLoading = true;

                    const mwLocations = JSON.parse('<?= $escaper->escapeJs(json_encode(['location_ids' => [(int)$location->getId()]]))?>');
                    mwLocations['store_id'] = <?= (int)$block->getCurrentStoreId()?>;

                    if (config.isWorkingHoursEnabled && typeof mwLocations !== 'undefined') {
                        this.isShowWorkInfo = true;
                        const url = '<?= $escaper->escapeJS($block->getWorkingHoursUrl()) ?>'
                            + '?_=' + new Date().getTime();

                        const body = new URLSearchParams({
                            form_key: hyva.getFormKey(),
                            "location_ids[]": mwLocations["location_ids"],
                            "store_id": mwLocations["store_id"],
                        });

                        fetch(url, {
                            method: 'post',
                            body,
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                                "X-Requested-With": "XMLHttpRequest"
                            }})
                            .then(response => {
                                if (! response.ok) console.warn('request failed');
                                return response.text();
                            })
                            .then(data => {
                                const dataObject = JSON.parse(data);

                                for (const key in dataObject) {
                                    const {isOpen, info} = dataObject[key];
                                    const locationCode = key;

                                    if (isOpen !== undefined && info) {
                                        const $info = document.getElementById("mw_store_info_" + locationCode);
                                        const $wh = document.getElementById("mw_store_info_wh_" + locationCode);

                                        this.isOpen = isOpen;
                                        this.workInfo = isOpen ? config.openNow : config.closedNow;
                                        this.workInfoWh = info;
                                    }
                                }
                            })
                            .catch(error => {
                                console.log(error)
                            })
                            .finally(() => {
                                this.isLoading = false
                            })
                    }
                },
                isShowWorkInfo: false,
                isLoading: false,
                isOpen: false,
                workInfo: null,
                workInfoWh: null,
            }
        }
    </script>

    <div id="mw-store-locator-details-page" x-data="initMwLocatorDetailsPage()">
        <?= $block->getMapHtml($location) ?>
        <div class="flex flex-col gap-y-8">
            <div class="bg-gray-100 px-4">
                <h2 class="text-xl p-4 text-center font-bold">
                    <?= $escaper->escapeHtml($location->getName()) ?>
                </h2>
                <ul class="flex flex-wrap justify-between py-4 items-center gap-y-4">
                    <li class="flex gap-x-2 items-center">
                        <?= $heroicons->locationMarkerHtml('w-8 h-8') ?>
                        <div>
                            <p>
                                <?= $escaper->escapeHtml($location->getAddress()); ?>, <?=
                                $escaper->escapeHtml($location->getCity()); ?>
                            </p>
                            <p>
                                <?= $location->getRegion() == \MageWorx\Locations\Model\Source\Region::NO_REGIONS ? '' :
                                    $escaper->escapeHtml($location->getRegion()) . ', '; ?>
                                <?= $escaper->escapeHtml($location->getPostcode()); ?> <?=
                                $escaper->escapeHtml($location->getCountry()); ?>
                            </p>
                        </div>

                    </li>
                    <li class="flex gap-x-2 items-center">
                        <?= $heroicons->mapHtml('w-8 h-8') ?>
                        <a href="<?= $escaper->escapeUrl($block->getRouteUrl($location)); ?>" target="_blank"><?=
                            $escaper->escapeHtml(__('Get direction')) ?></a>
                    </li>
                    <?php if ($location->getPhoneNumber()) : ?>
                        <li class="flex gap-x-2 items-center">
                            <?= $heroicons->phoneHtml('w-8 h-8') ?>
                            <a href="tel:<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getPhoneNumber())); ?>">
                                <?= $escaper->escapeHtml($location->getPhoneNumber()); ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <li class="flex gap-x-2 items-center" x-show="isShowWorkInfo">
                        <?= $heroicons->clockHtml('w-8 h-8') ?>
                        <div style="border-top-color:transparent" x-show="isLoading"
                             class="w-8 h-8 p-2 border-4 border-primary border-solid rounded-full animate-spin"></div>
                        <span :class="{'text-red-500': !isOpen, 'text-green-500': isOpen}" x-text="workInfo"></span>
                        <span :class="{'text-red-500': !isOpen, 'text-green-500': isOpen}" x-text="workInfoWh"></span>
                    </li>
                </ul>
            </div>
            <div class="px-4">
                <div class="flex flex-wrap gap-y-8 justify-between">
                    <div class="flex flex-col gap-y-8">
                        <?php if ($location->getDescription()) : ?>
                            <h2 class="text-xl font-bold"><?= $escaper->escapeHtml(__('Store description')) ?></h2>
                            <p><?= /** @noEscape */ $location->getDescription(); ?></p>
                        <?php endif; ?>
                        <ul class="flex flex-col gap-y-4">
                            <?php if ($location->getEmail()) : ?>
                                <li class="flex gap-x-2 items-center">
                                    <?= $heroicons->atSymbolHtml('w-6 h-6') ?>
                                    <a href="mailto:<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getEmail())); ?>">
                                        <?= $escaper->escapeHtml($location->getEmail()); ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($location->getWebsiteUrl()) : ?>
                                <li class="flex gap-x-2 items-center">
                                    <?= $heroicons->globeAltHtml('w-6 h-6') ?>
                                    <a href="https://<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getWebsiteUrl())); ?>"
                                        target="_blank">
                                        <?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getWebsiteUrl())); ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                        <ul class="flex gap-x-4 mt-4">
                            <?php if ($location->getInstagram()) : ?>
                                <li>
                                    <a href="https://instagram.com/<?= $escaper->escapeHtmlAttr($escaper->escapeUrl(
                                            $location->getInstagram()
                                        )); ?>" target="_blank">
                                        <i>
                                            <img
                                                src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getViewFileUrl(
                                                    'MageWorx_StoreLocator::images/svg/instagram.svg'
                                                ))); ?>"
                                                alt="<?= $escaper->escapeHtml(__('Instagram icon')) ?>"/>
                                        </i>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($location->getFacebook()) : ?>
                                <li>
                                    <a href="https://facebook.com/<?= $escaper->escapeHtmlAttr($escaper->escapeUrl(
                                            $location->getFacebook()
                                        )); ?>" target="_blank">
                                        <i>
                                            <img
                                                src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getViewFileUrl(
                                                    'MageWorx_StoreLocator::images/svg/facebook.svg'
                                                ))); ?>"
                                                alt="<?= $escaper->escapeHtml(__('Facebook icon')) ?>"/>
                                        </i>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($location->getWhatsapp()) : ?>
                                <li>
                                    <a href="https://wa.me/<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getWhatsapp())); ?>"
                                       target="_blank">
                                        <i>
                                            <img
                                                src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getViewFileUrl(
                                                    'MageWorx_StoreLocator::images/svg/whatsapp.svg'
                                                ))); ?>"
                                                alt="<?= $escaper->escapeHtml(__('Whatsapp icon')) ?>"/>
                                        </i>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($location->getSkype()) : ?>
                                <li>
                                    <a href="skype:<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($location->getSkype())); ?>?call">
                                        <i>
                                            <img src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getViewFileUrl(
                                                'MageWorx_StoreLocator::images/svg/skype.svg'
                                            ))); ?>" alt="<?= $escaper->escapeHtml(__('Skype icon')) ?>"/>
                                        </i>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <?php if ($location->getImagePath()) : ?>
                        <div class="pl-4">
                            <img class="h-32 w-auto"
                                src="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getLocationImageUrl($location->getImagePath()))); ?>"
                                alt="<?= $escaper->escapeHtml(
                                    $location->getName()
                                ) ?>"/>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="flex justify-center">
                <ul class="flex gap-x-6 items-center">
                    <?php foreach ($block->getExtraAttributes() as $attribute) : ?>
                        <?php if ($location->getData($attribute['attribute_code'])) : ?>
                            <li class="flex gap-x-2 items-center">
                                <i>
                                    <?php $icon = $block->getAttributeIcon($attribute['attribute_code']);
                                    if ($icon): ?>
                                        <img class="w-4 h-4"
                                             src="<?= $escaper->escapeUrl($icon); ?>"
                                             alt="<?= $escaper->escapeHtml(__($attribute['frontend_label'])) ?>"/>
                                    <?php endif;?>
                                </i>
                                <span><?= $escaper->escapeHtml(__($attribute['frontend_label'])) ?><span>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div>
                <?= $block->getWorkingHoursHtml($location) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
