<?php
declare(strict_types=1);

/**
 * Copyright © MageWorx. All rights reserved.
 * See https://www.mageworx.com/terms-and-conditions for license details.
 */

?>
<?php
/**
 * Location Page view template
 *
 * @var $block MageWorx\LocationPages\Block\Map
 */
/** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
$location = $block->getLocation();

/** @var $escaper \Magento\Framework\Escaper */
?>

<?php if ($block->isShowMap()) : ?>
    <script>
        function initMwMapLocator() {
            return {
                init() {
                    const googleMapsApiUrl = "https://maps.googleapis.com/maps/api/js?key=<?= $escaper->escapeHtml($block->getApiKey())?>";

                    const loadMap = () => {
                        const location = <?= $escaper->escapeHtml($block->getLocationCoordinate($location))?>;
                        const mapOptions = {
                            center: new google.maps.LatLng(location),
                            zoom: 12,
                            mapTypeId: google.maps.MapTypeId.roadmap,
                            disableDefaultUI: true
                        };

                        map = new google.maps.Map(document.getElementById("mw-sl-map"), mapOptions);

                        const marker = new google.maps.Marker({
                            position: location,
                            icon: '<?= $escaper->escapeHtml($block->getMapIcon())?>',
                            map: map
                        });
                    }

                    if (typeof google == 'undefined' || typeof google.maps == 'undefined') {
                        const script = document.createElement('script');
                        script.setAttribute("async", "");
                        script.setAttribute("defer", "");
                        script.src = googleMapsApiUrl;
                        document.head.append(script);
                        script.addEventListener("load", loadMap);
                    }
                    else {
                        loadMap();
                    }
                }
            }
        }
    </script>

    <div class="w-full h-72" id="mw-sl-map" x-data="initMwMapLocator()"></div>
<?php endif; ?>
