<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();

?>
<div class="container flex pt-6 pb-3 mx-auto mb-6 border-b-2 border-gray-300 md:flex-row">
    <h2 class="w-full text-2xl text-center text-gray-900 title-font font-base md:text-left">
        <?= $escaper->escapeHtml(__('Description')) ?> /
        <span id="product-name" class="font-semibold"><?= $escaper->escapeHtml($product->getName()) ?></span>
    </h2>
</div>
