<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.it)
 * @package One Step Checkout Delivery Date for Magento 2 (System)
 */
/** @var \Armah\CheckoutDeliveryDate\Block\Sales\Order\Info\Delivery $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($fields = $block->getDeliveryDateFields()): ?>
    <div class="delivery">
    <?php foreach ($fields as $field): ?>
        <div class="delivery-field">
            <?= $escaper->escapeHtml(__($field['label'])); ?> : <?= $escaper->escapeHtml($field['value']); ?>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif ?>
