<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;


// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Template $block */
/** @var SearchHelper $helper */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$helper = $this->helper(SearchHelper::class);
?>
<script>
    'use strict';

    function initMiniSearch() {
        return {
            minSearchLength: <?= (int) $helper->getMinQueryLength() ?>,
            suggestions: [],
            suggest() {
                const search = this.$refs.searchInput;
                if (search.value.length >= this.minSearchLength) {
                    search.setCustomValidity('');
                    search.reportValidity();
                    this.fetchSuggestions(search.value);
                } else {
                    this.suggestions = [];
                }
            },
            fetchSuggestions(term) {
                fetch(
                    window.BASE_URL + 'search/ajax/suggest?' + new URLSearchParams({q: term}),
                    {
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest'
                        }
                    }
                )
                .then(response => response.json())
                .then(result => this.suggestions = result);
            },
            search(term) {
                const search = this.$refs.searchInput;
                term = term || search.value;
                if (term.length < this.minSearchLength) {
                    search.setCustomValidity('<?= $escaper->escapeJs(
                        __(
                            "Minimum Search query length is %1",
                            $helper->getMinQueryLength()
                        )
                    ) ?>');
                    search.reportValidity();
                } else {
                    search.setCustomValidity('');
                    search.value = term;
                    this.$refs.form.submit();
                }
            },
            focusElement(element) {
                if (element && element.nodeName === "DIV") {
                    element.focus();
                    return true;
                } else {
                    return false;
                }
            }
        }
    }
</script>
<div class="container p-0 mx-auto text-black" x-data="initMiniSearch()">
    <form class="relative px-6 py-4 form minisearch lg:px-0 lg:py-0" id="search_mini_form" x-ref="form" @submit.prevent="search()"action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__("Search")) ?></span>
        </label>
        <input id="search"
               x-ref="searchInput"
               type="search"
               autocomplete="off"
               name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
               value="<?= /** @noEscape */ $helper->getEscapedQueryText() ?>"
               placeholder="<?= $escaper->escapeHtmlAttr(__("Search entire store here...")) ?>"
               maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
               class="w-full h-10 p-2 pr-10 text-sm leading-normal transition border-2 rounded-lg appearance-none border-rosso text-grey-800 focus:border-rosso focus:ring-0 lg:text-sm border-backgrey-700"
               @focus.once="suggest"
               @input.debounce.300="suggest"
               @keydown.arrow-down.prevent="focusElement($el.querySelector('[tabindex]'))"
        />
        <button class="absolute top-0 w-16 h-full bg-transparent right-4 lg:hidden" type="submit">
        <?= $heroicons->searchHtml('text-black lg:text-gray-400 border-current inline w-6 lg:w-7 h-7 lg:h-8'); ?>
        </button>
         <template x-if="suggestions.length > 0">
             <div class="absolute right-0 flex flex-col w-full mt-1 leading-normal text-gray-800 transition appearance-none">
                 <template x-for="suggestion in suggestions">
                     <div class="flex justify-between p-2 border cursor-pointer bg-container-lighter even:bg-container border-container last-of-type:rounded hover:bg-container-darker"
                          tabindex="0"
                          @click="search(suggestion.title)"
                          @keydown.enter="search(suggestion.title)"
                          @keydown.arrow-up.prevent="
                              focusElement($event.target.previousElementSibling) || $refs.searchInput.focus()
                          "
                          @keydown.arrow-down.prevent="focusElement($event.target.nextElementSibling)"
                     >
                         <span x-text="suggestion.title"></span>
                         <span x-text="suggestion.num_results"></span>
                     </div>
                 </template>
             </div>
         </template>
        <button type="submit"
                title="<?= $escaper->escapeHtml(__("Search")) ?>"
                class="absolute top-0 right-0 items-center justify-center hidden w-10 h-10 bg-transparent rounded lg:flex action search"
                aria-label="Search"
        >
            <?= $heroicons->searchHtml('text-black border-current inline'); ?>
        </button>
    </form>
</div>
