<?php
/**
 * @author Armah Team
 * @copyright Copyright (c) Armah (https://www.armah.com)
 * @package Seo Toolkit Core Hyva Compatibility
 */

use Armah\SeoToolkitLite\Block\Toolbar;
use Armah\SeoToolkitLiteHyva\ViewModel\Toolbar as ToolbarViewModel;
use Armah\SeoToolkitLiteHyva\ViewModel\ToolkitIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var Hyva\Theme\ViewModel\HyvaCsp|null $hyvaCsp */

$toolkitIcons = $viewModels->require(ToolkitIcons::class);
$heroIconsOutline = $viewModels->require(HeroiconsOutline::class);
$toolbarViewModel = $viewModels->require(ToolbarViewModel::class);
$images = $block->getImagesWithoutAlt();
?>
<div x-data="initArToolbar"
     data-images-length="<?= $escaper->escapeHtmlAttr(count($images)) ?>"
     :class="toolbarCssClasses"
     role="dialog"
     aria-labelledby="arskit-toolbar-title"
     class="arskit-toolbar-wrap z-50 fixed rounded-xl shadow-md bg-white bottom-0 left-0 w-full
            sm:h-auto sm:bottom-6 sm:left-6 sm:max-w-[500px]">
    <button @click="toggleOpen"
            :class="buttonCssClasses"
            :aria-expanded="ariaExpanded"
            aria-controls="arskit-toolbar-content"
            type="button"
            class="arskit-toolbar-box w-full flex flex-row items-center px-4 py-3 bg-gray-200 rounded-xl cursor-pointer">
        <span class="arskit-toolbar-icon" aria-hidden="true">
            <?= $toolkitIcons->toolbarHtml('', 30, 30) ?>
        </span>
        <span class="flex items-center">
            <span id="arskit-toolbar-title" class="arskit-title text-lg font-semibold leading-8 ml-3">
                <?= $escaper->escapeHtml(__('Seo Toolbar')) ?>
            </span>
        </span>
        <span class="flex items-center ml-auto" :class="chevronCssClasses">
            <?= $heroIconsOutline->chevronUpHtml() ?>
        </span>
    </button>

    <div x-show="isOpen"
         tabindex="0"
         id="arskit-toolbar-content"
         class="arskit-toolbar-content overflow-x-hidden overflow-auto max-h-[calc(95vh-5rem)]">
        <div class="arskit-title font-semibold px-3 pt-4">
            <div class="border-b pb-3 flex justify-between items-center">
                <div>
                    <?= $escaper->escapeHtml(__('Page Analysis')) ?>
                </div>
                <?= $block->getChildHtml('armah_seotoolbar_header');?>
            </div>
        </div>
        <table class="arskit-table w-full mt-3 table-fixed text-sm">
            <thead>
            <tr>
                <th class="w-1/3 sr-only"><?= $escaper->escapeHtml(__('Parameter Name')) ?></th>
                <th class="w-2/3 sr-only"><?= $escaper->escapeHtml(__('Parameter Value')) ?></th>
            </tr>
            </thead>
            <tbody class="align-top">
            <tr>
                <td class="pl-3"><?= $escaper->escapeHtml(__('Robots Meta')) ?></td>
                <td class="arskit-cell pr-3 pl-7"><?= $escaper->escapeHtml($block->getRobotsMeta()) ?></td>
            </tr>
            <tr>
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Canonical')) ?></td>
                <td class="arskit-cell pr-3 pt-3 flex">
                    <?php list($text, $status) = $block->getCanonicalText() ?>
                    <div class="mr-2">
                        <?= /** @noEscape */ $toolbarViewModel->getToolkitIconByStatus($status) ?>
                    </div>
                    <div>
                        <?= $escaper->escapeHtml($text) ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Title')) ?></td>
                <td class="arskit-cell pt-3 pr-3 flex">
                    <?php list($text, $status) = $block->getTitleCount() ?>
                    <div class="mr-2"
                        <?php if ($status === $block::WARNING_CLASS): ?>
                            data-artoolbar-js="title"
                        <?php endif; ?>>
                        <?= /** @noEscape */ $toolbarViewModel->getToolkitIconByStatus($status) ?>
                    </div>
                    <div class="flex flex-col">
                        <div>
                            <?= $escaper->escapeHtml($text) ?>
                        </div>
                        <div class="arskit-description text-xs text-gray-500">
                            <?php if ($block->getTitleText()): ?>
                                <?= $escaper->escapeHtml($block->getTitleText()) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml(__('Try to enlarge it to %1 characters.', $block->getMaxTitleLength())) ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Meta Description')) ?></td>
                <td class="arskit-cell pr-3 pt-3 flex">
                    <?php list($text, $status) = $block->getMetaDescCount() ?>
                    <div class="mr-2"
                        <?php if ($status === $block::WARNING_CLASS): ?>
                            data-artoolbar-js="description"
                        <?php endif; ?>>
                        <?= /** @noEscape */ $toolbarViewModel->getToolkitIconByStatus($status) ?>
                    </div>
                    <div class="flex flex-col">
                        <div>
                            <?= $escaper->escapeHtml($text) ?>
                        </div>
                        <div class="arskit-description text-xs text-gray-500">
                            <?php if ($block->getMetaDescText()): ?>
                                <?= $escaper->escapeHtml($block->getMetaDescText()) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml(__('Try to enlarge it to %1 characters.', $block->getMetaDescLength())) ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Headings')) ?></td>
                <td class="arskit-cell pr-3 pt-3">
                    <?php list($headings, $status) = $block->getHeadings() ?>
                    <div class="arskit-headings-wrap flex w-full">
                        <div class="mr-2">
                            <?= /** @noEscape */ $toolbarViewModel->getToolkitIconByStatus($status) ?>
                        </div>
                        <div class="flex flex-row flex-wrap">
                            <?php foreach ($headings as $name => $text): ?>
                                <div class="arskit-item ml-2 first:ml-0">
                                    <div class="arskit-head uppercase">
                                        <?= $escaper->escapeHtml('<' . $name . '>') ?>
                                    </div>
                                    <div class="text-center"><?= count($text) ?></div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="arskit-description text-xs text-gray-500 pl-7 mt-2">
                        <?= $escaper->escapeHtml($block->stripTags(implode(', ', $headings['h1']))) ?>
                    </div>
                </td>
            </tr>

            <?php if ($images): ?>
                <tr>
                    <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Images')) ?></td>
                    <td class="arskit-cell pt-3 pr-3 pb-3">
                        <div class="flex flex-row">
                            <div class="mr-2">
                                <?= /** @noEscape */ $toolbarViewModel->getToolkitIconByStatus($block::WARNING_CLASS) ?>
                            </div>
                            <div>
                                <?= $escaper->escapeHtml(__('%1 image(s) without ALT tag', count($images))) ?>
                            </div>
                        </div>
                        <div class="arskit-description pl-7 flex flex-col">
                            <?php foreach ($images as $img): ?>
                                <span class="arskit-url text-gray-500 break-words"><?= $escaper->escapeHtml($img) ?></span>
                            <?php endforeach; ?>
                            <template x-if="canShowMoreButton">
                                <div class="flex flex-row w-full justify-center items-center mt-2">
                                    <hr class="flex-grow">
                                    <div>
                                        <button type="button"
                                                @click="clickOther"
                                                class="border rounded-full px-4 py-1 text-xs text-gray-500">
                                            <?= $escaper->escapeHtml(__('other')) ?>
                                            <span x-text="textOther"></span>
                                        </button>
                                    </div>
                                    <hr class="flex-grow">
                                </div>
                            </template>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
            <tr class="bg-gray-100">
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('In-Page Links')) ?></td>
                <td class="arskit-cell pl-7 pr-3 pt-3">
                    <ul class="arskit-page-links">
                        <?php foreach ($block->getLinksData() as $link => $linkData): ?>
                            <li class="arskit-item relative pl-3 mb-3 before:absolute before:top-1/2 before:-translate-y-1/2
                                    before:left-0 before:bg-blue-400 before:w-[5px] before:h-[5px] before:rounded-full">
                                    <span class="arskit-label inline-block w-1/2">
                                        <?= $escaper->escapeHtml($linkData['label']) ?>
                                    </span>
                                <span class="arskit-count">
                                        <?= $escaper->escapeHtml($linkData['count']) ?>
                                    </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </td>
            </tr>
            <tr class="bg-gray-100">
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Schema.org Tags')) ?></td>
                <td class="arskit-cell pl-7 pr-3 pt-3">
                    <?php if ($block->isSchemaOrgExists()): ?>
                        <?= $escaper->escapeHtml(__('Great. We have found several schema.org types')) ?>
                    <?php else: ?>
                        <?= $escaper->escapeHtml(__('There are no schema.org types')) ?>
                    <?php endif; ?>
                </td>
            </tr>
            <tr class="bg-gray-100">
                <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Iframes')) ?></td>
                <td class="arskit-cell pl-7 p-3">
                    <?= $escaper->escapeHtml($block->getIframeText()) ?>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="arskit-title font-semibold px-3 pt-4">
            <div class="border-b pb-3">
                <?= $escaper->escapeHtml(__('Page Content')) ?>
            </div>
        </div>
        <table class="arskit-table w-full mt-3 table-fixed text-sm mb-5">
            <thead>
            <tr>
                <th class="w-1/3 sr-only"><?= $escaper->escapeHtml(__('Parameter Name')) ?></th>
                <th class="w-2/3 sr-only"><?= $escaper->escapeHtml(__('Parameter Value')) ?></th>
            </tr>
            </thead>
            <tbody class="align-top">
            <tr>
                <td class="pl-3"><?= $escaper->escapeHtml(__('State')) ?></td>
                <td class="arskit-cell pl-7 pr-3"><?= $escaper->escapeHtml($block->getPageState()) ?></td>
            </tr>
            <?php $metaTag = $block->getMetaTagTemplateData() ?>
            <?php if ($metaTag): ?>
                <tr>
                    <td class="pl-3 pt-3"><?= $escaper->escapeHtml(__('Applied Meta Tags Template')) ?></td>
                    <td class="arskit-cell pl-7 pt-3 pr-3">
                        <?php foreach ($metaTag as $template): ?>
                            <div><?= $escaper->escapeHtml($template) ?></div>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

