<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Dashboard\Address;
use Magento\Framework\Escaper;

/** @var Address $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="block block-dashboard-addresses">
    <div class="flex items-center justify-between my-6 border block-title card">
        <span class="block text-2xl"><?= $escaper->escapeHtml(__('Address Book')) ?></span>
        <a class="inline-block border-b-2 action edit border-arancio-300"
           href="<?= $escaper->escapeUrl($block->getAddressBookUrl()) ?>">
           <span><?= $escaper->escapeHtml(__('Manage Addresses')) ?></span>
        </a>
    </div>
    <div class="block-content">
        <div class="flex flex-wrap justify-between -m-4">
            <div class="w-full p-4 lg:w-1/2">
                <div class="flex flex-col h-full p-8 border sm:flex-row card">
                    <div class="flex-grow">
                        <h2 class="mb-3 text-xl font-medium text-gray-900 title-font">
                            <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                        </h2>
                        <address>
                            <?= $block->getPrimaryBillingAddressHtml() ?>
                        </address>
                        <a
                            class="inline-flex items-center w-full mt-3 text-secondary hover:text-secondary-darker"
                            href="<?= $escaper->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>"
                            data-ui-id="default-billing-edit-link"><span class="border-b-2 border-arancio-300"><?= $escaper->escapeHtml(
                                __('Edit Address')
                            ) ?></span>
                            <?= $heroicons->arrowRightHtml('ml-2', 16, 16); ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="w-full p-4 lg:w-1/2">
                <div class="flex flex-col h-full p-8 border sm:flex-row card">
                    <div class="flex-grow">
                        <h2 class="mb-3 text-xl font-medium text-gray-900 title-font">
                            <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                        </h2>
                        <address>
                            <?= $block->getPrimaryShippingAddressHtml() ?>
                        </address>
                        <a
                            class="inline-flex items-center w-full mt-3 text-secondary hover:text-secondary-darker"
                            href="<?= $escaper->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>"
                            data-ui-id="default-billing-edit-link"><span class="border-b-2 border-arancio-300"><?= $escaper->escapeHtml(
                                __('Edit Address')
                            ) ?></span>
                            <?= $heroicons->arrowRightHtml('ml-2', 16, 16); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
